system:
  name: "video-search"
  version: "1.0.0"

frame_extraction:
  sample_rate: 1.0  # fps
  max_frames_per_video: 3600
  frame_size: [224, 224]
  scene_detection_threshold: 30.0

feature_extraction:
  model_name: "clip-vit-base-patch32"
  batch_size: 32
  device: "auto"  # auto, cuda, cpu
  dimension: 512

index:
  type: "hnsw"
  dimension: 512
  
  # HNSW specific - optimized for speed
  hnsw:
    M: 16  # Number of bidirectional links
    ef_construction: 200  # Size of dynamic candidate list
    ef_search: 50  # Size of dynamic candidate list during search
    max_M: 16
    level_generation_factor: 1.0 / math.log(2.0)

cache:
  l1_capacity: 2000  # In-memory cache size
  l2_host: "redis://localhost:6379"
  ttl_seconds: 300
  enable_cache: true

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  max_upload_size: 5368709120  # 5GB
  request_timeout: 30

monitoring:
  prometheus_port: 9090
  log_level: "INFO"
  enable_metrics: true

batch_processing:
  batch_size: 32
  timeout_ms: 10
  max_concurrent_batches: 4

performance:
  use_memory_mapping: true
  enable_gpu_acceleration: true
  num_threads: 4
